### ISSUE TITLE
Adopt Open JDK 8 tap missing

### ISSUE THREAD

**Issue by mxdvl** [guardian/strap#12]
## Expected Behavior

Install the correct Java versions. Do we need v8 / `adoptopenjdk8`? I thought we were using v11 now.

## Actual Behavior

```sh
Error: Cask 'adoptopenjdk/openjdk/adoptopenjdk8' is unavailable.
Please tap it and then try again: brew tap adoptopenjdk/openjdk
```

## Steps to Reproduce the Problem

  1. `brew install --cask gu-base`

## Specifications

  - Mac OS Version: 11.5.2
  - Homebrew Version: Homebrew 3.2.15-2-g4d5af40

**Comment by georgeblahblah** [comment]
I think we are still using v8 in some places, like on `guardian/identity` (https://github.com/guardian/identity/blob/main/.sdkmanrc)

You _should_ be able to get around this error by following https://stackoverflow.com/a/56981661, and then re-running strap / `brew install --cask gu-base`

If v8 is now a "special case", we could remove it from here and install it as needed.

**Comment by iainjchambers-guardian** [comment]
I managed to install all of the dependencies manually using the following: 
```
brew install openssl wget ack jq bash-completion coreutils git hub gnupg htop mtr tree watch awscli nginx
brew install adoptopenjdk/openjdk/adoptopenjdk8 gu-scala node yarn
brew install guardian/devtools/ssm guardian/devtools/dev-nginx
brew install keepingyouawake iterm2 homebrew/cask-versions/firefox-developer-edition visualvm intellij-idea gpg-suite postman vlc rectangle licecap session-manager-plugin
```
Just thought I'd share that if it'll save anyone ten minutes down the line.

**Comment by akash1810** [comment]
https://github.com/guardian/homebrew-devtools/pull/79 proposes pushing the responsibility to the user. This provides two benefits:
  1. Less to maintain
  2. Users can choose to use `sdkman`, `coursier`, `asdf` etc to manage Java versions (similar argument for Node applies)

**Comment by mxdvl** [comment]
Happy with those suggestions 🚀
