### ISSUE TITLE
Strap fails if application(s) are pre-installed

### ISSUE THREAD

**Issue by JustinPinner** [guardian/strap#9]
## Expected Behaviour
Upgrade or prompt to replace an existing application if encountered

## Actual Behaviour
```
==> Installing Cask vlc
==> Purging files for version 3.0.11.1 of Cask vlc
Error: It seems there is already an App at '/Applications/VLC.app'.
!!! Executing 'brew install --cask gu-base': FAILED
```

## Steps to Reproduce the Problem
* Run strap.sh with (any?) of the applications listed in the [# gui apps](https://github.com/guardian/homebrew-devtools/blob/master/Casks/gu-base.rb#L38) section of `gu-base.rb` already installed.

## Specifications

  - Mac OS Version: Mojave (10.14.3)
  - Homebrew Version: 2.7.1

**Comment by akash1810** [comment]
The described issue should no longer occur following the changes in https://github.com/guardian/homebrew-devtools/pull/79. Closing.
